# Generated by Django 4.2 on 2023-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMart2', '0003_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='TotalPrice',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
