# Generated by Django 4.2 on 2023-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMart2', '0004_alter_cartdb_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Email', models.EmailField(blank=True, max_length=500, null=True)),
                ('Town', models.CharField(blank=True, max_length=500, null=True)),
                ('Phone', models.IntegerField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
