# Generated by Django 4.2 on 2023-05-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMart', '0002_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='Image',
            new_name='ProductImage',
        ),
    ]
